In [16]:
import os
import pandas as pd

In [17]:
cwd = os.getcwd()
df = pd.read_csv(cwd + "\\bcg-financial-data.csv")
df = df.drop(columns=["Unnamed: 0"], errors = 'ignore')

In [13]:
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Asset Growth (%),Liabilities Growth (%),Cash Flow Growth (%)
0,Apple,2022,394328,99803,352755,302083,122151,0.000000,0.000000,0.000000,0.000000,0.000000
1,Apple,2023,383285,96995,352583,290437,110543,-2.800461,-2.813543,-0.048759,-3.855232,-9.502992
2,Apple,2024,391035,93736,364980,308030,118254,2.021994,-3.359967,3.516052,6.057424,6.975566
3,Microsoft,2022,198270,72738,364840,198298,89035,0.000000,0.000000,0.000000,0.000000,0.000000
4,Microsoft,2023,211915,72361,411976,205753,87582,6.882030,-0.518299,12.919636,3.759493,-1.631942
5,Microsoft,2024,245122,88136,512163,243686,118548,15.669962,21.800417,24.318650,18.436183,35.356580
6,Tesla,2022,81462,12587,82338,36440,14724,0.000000,0.000000,0.000000,0.000000,0.000000
7,Tesla,2023,96773,14974,106618,43009,13256,18.795267,18.964010,29.488207,18.026894,-9.970117
8,Tesla,2024,97690,7153,122070,48390,14923,0.947578,-52.230533,14.492862,12.511335,12.575438

In [9]:
# Make chatbot using if else statements
def financial_chatbot():
    print("\nWelcome to the Financial Chatbot! Type 'exit' to quit.")
    
    while True:
        company = input("Enter company (Apple, Microsoft, Tesla): ").capitalize()
        if company not in df['Company'].unique():
            print("Invalid company. Try again.")
            continue

        try:
            year = int(input("Enter year (2022, 2023, 2024): "))
        except ValueError:
            print("Invalid year. Try again.")
            continue

        if year not in df['Year'].unique():
            print("Year not in dataset. Try again.")
            continue

        print("\nAsk a question (e.g., 'What is the total revenue?')")
        query = input().lower()

        data_row = df[(df['Company'] == company) & (df['Year'] == year)]
        if data_row.empty:
            print("No data found for the given inputs.")
            continue
        
        if "total revenue" in query:
            print(f"Total Revenue for {company} in {year}: ${data_row['Total Revenue'].values[0]} million")
        elif "net income" in query:
            print(f"Net Income for {company} in {year}: ${data_row['Net Income'].values[0]} million")
        elif "total assets" in query:
            print(f"Total Assets for {company} in {year}: ${data_row['Total Assets'].values[0]} million")
        elif "total liabilities" in query:
            print(f"Total Liabilities for {company} in {year}: ${data_row['Total Liabilities '].values[0]} million")
        elif "cash flow" in query:
            print(f"Cash Flow from Operations for {company} in {year}: ${data_row['Cash Flow from Operating Activities'].values[0]} million")
        elif "growth" in query:
            if "revenue" in query:
                print(f"Revenue Growth for {company} in {year}: {data_row['Revenue Growth (%)'].values[0]}%")
            elif "net income" in query:
                print(f"Net Income Growth for {company} in {year}: {data_row['Net Income Growth (%)'].values[0]}%")
            elif "assets" in query:
                print(f"Asset Growth for {company} in {year}: {data_row['Asset Growth (%)'].values[0]}%")
            elif "liabilities" in query:
                print(f"Liabilities Growth for {company} in {year}: {data_row['Liabilities Growth (%)'].values[0]}%")
            elif "cash flow" in query:
                print(f"Cash Flow Growth for {company} in {year}: {data_row['Cash Flow Growth (%)'].values[0]}%")
            else:
                print("Invalid growth query. Try again.")
        else:
            print("Sorry, I can't answer that. I can only answer predefined financial queries.")

In [ ]:
# To run the chatbot
if __name__ == "__main__":
    financial_chatbot()

The main problem with the chatbot is that if you don't know the entire dataset, you won't ask certain questions. Instead, there should be some guidance, or some options available for the user to better understand the dataset that they are working with. Also there is no way to just quit/exit right after getting the information. The user has to keep going essentially.

In [23]:
#chatbot version 2, trying to make it better than the previous one
def financial_chatbot_v2():
    print("\nWelcome to the Financial Chatbot v2! (way better than the previous one!)")
    print("I can help you with financial queries for Apple, Microsoft, and Tesla.")
    
    while True:
        #Pick company 
        print("\nWhich company's data would you like to explore?")
        print("1. Apple\n2. Microsoft\n3. Tesla")
        company_input = input("Enter company name: ").capitalize()

        if company_input not in ["Apple", "Microsoft", "Tesla"]:
            print("\nInvalid Company Name. Please try again.")
            continue

        # Choose Year
        print("\nThe available years are 2022, 2023, and 2024.")
        try:
            fiscal_year = int(input("Enter the year: "))
            if fiscal_year not in [2022, 2023, 2024]:
                print("\nInvalid year. Please try again.")
                continue
        except ValueError:
            print("\nInvalid input. Please enter a valid year.")
            continue

        # Info user would like to know about the selected company in selected year
        query_map = {
            "1": "Total Revenue",
            "2": "Net Income",
            "3": "Total Assets",
            "4": "Total Liabilities ",
            "5": "Cash Flow from Operating Activities"
        }
        
        if fiscal_year != 2022:  # Growth options only for 2023 & 2024 (since 2022 is base year and growth rates would be 0%)
            query_map.update({
                "6": "Revenue Growth (%)",
                "7": "Net Income Growth (%)",
                "8": "Asset Growth (%)",
                "9": "Liabilities Growth (%)",
                "10": "Cash Flow Growth (%)"
            })

        # Display options options
        print("\nWhat would you like to know about the company?")
        for key, value in query_map.items():
            print(f"{key}. {value}")

        choice = input("Enter the number of your choice: ")

        if choice in query_map:
            column = query_map[choice]
            result = df[(df["Company"] == company_input) & (df["Year"] == fiscal_year)][column]

            if not result.empty:
                value = result.values[0]
                # Format growth % correctly
                if "Growth (%)" in column:
                    print(f"\n{column} for {company_input} in {fiscal_year}: {value:.2f}%")
                else:
                    print(f"\n{column} for {company_input} in {fiscal_year}: {value} million")
            else:
                print("\nData not found. Please try again.")
        else:
            print("\nInvalid choice. Please try again.")
            continue

        # Ask if user wants to know more
        more_help = input("\nIs there anything else I can help you with? (yes/no): ").strip().lower()
        if more_help not in ["yes", "y", "yeah", "yea"]:
            print("\nThank you for using the chatbot. Have a great day!")
            break

In [24]:
if __name__ == "__main__":
    financial_chatbot_v2()

Welcome to the Financial Chatbot v2! (way better than the previous one!)
I can help you with financial queries for Apple, Microsoft, and Tesla.

Which company's data would you like to explore?
1. Apple
2. Microsoft
3. Tesla
Enter company name: Microsoft

The available years are 2022, 2023, and 2024.
Enter the year: 2022

What would you like to know about the company?
1. Total Revenue
2. Net Income
3. Total Assets
4. Total Liabilities
5. Cash Flow from Operating Activities
Enter the number of your choice:

Invalid choice. Please try again.

Which company's data would you like to explore?
1. Apple
2. Microsoft
3. Tesla
Enter company name: Microsoft

The available years are 2022, 2023, and 2024.
Enter the year: 2022

What would you like to know about the company?
1. Total Revenue
2. Net Income
3. Total Assets
4. Total Liabilities
5. Cash Flow from Operating Activities
Enter the number of your choice: 4

Total Liabilities  for Microsoft in 2022: 198298 million

Is there anything else I can help you with? (yes/no): yes

Which company's data would you like to explore?
1. Apple
2. Microsoft
3. Tesla
Enter company name: Apple

The available years are 2022, 2023, and 2024.
Enter the year: 2023

What would you like to know about the company?
1. Total Revenue
2. Net Income
3. Total Assets
4. Total Liabilities
5. Cash Flow from Operating Activities
6. Revenue Growth (%)
7. Net Income Growth (%)
8. Asset Growth (%)
9. Liabilities Growth (%)
10. Cash Flow Growth (%)
Enter the number of your choice: 8

Asset Growth (%) for Apple in 2023: -0.05%

Is there anything else I can help you with? (yes/no): nope

Thank you for using the chatbot. Have a great day!

This version in my opinion is better. It gives the user all the options and asks the user if they would like to request more information rather than just assuming like the previous if else version.